baseURL = "https://nyaannyaan.github.io/blog"
languageCode = "ja"
title = "test title"
contentDir = "posts"
theme = "ananke"
[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
