baseURL = "https://nyaannyaan.github.io/blog"
languageCode = "ja"
title = "Living with OFUTON"
contentDir = "posts"
theme = "ananke"

[params]
  body_classes = "avenir bg-near-white"
  post_content_classes = "code"
  custom_css = ["css/zumen.css"]

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
